name: web-messenger

volumes:
  web-messenger-data:
    external: true

services:
  web-messenger-db:
    image: postgres:latest
    restart: always
    container_name: web-messenger-db
    environment:
      - POSTGRES_DB=mydata
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
    ports:
      - 5432:5432
    volumes:
      - web-messenger-data:/var/lib/postgresql/data
