name: web-messenger

volumes:
  web-messenger-data:
    external: true

networks:
  web-messenger-network:
    external: true

services:
  web-messenger-db:
    image: postgres:latest
    restart: always
    container_name: web-messenger-db
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - web-messenger-data:/var/lib/postgresql/data
    networks:
      - web-messenger-network
  web-messenger-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: web-messenger-backend
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_TOKEN_LIFE_TIME_IN_MS=${JWT_TOKEN_LIFE_TIME_IN_MS}
    ports:
      - 8080:8080
    networks:
      - web-messenger-network
    depends_on:
      - web-messenger-db